### ISSUE TITLE
Incorrect answer to question 8

### ISSUE THREAD

**Issue by atxrenegade** [learn-co-curriculum/js-data-structures-objects-and-arrays-quiz#1]
Question #8: What is the result of the following code in a browser that supports the spread operator?

const oneTwoThree = [1, 2, 3]
const sevenEightNine = [7, 8, 9]
 
[4, 5, 6, ...oneTwoThree, ...sevenEightNine]

I copied and pasted this code into three different browser consoles: GoogleChrome, Safari and Brave all 3 threw the same error: Uncaught SyntaxError: Unexpected token ...  

What variable is this new array being stored in?

Test says answer should be [4, 5, 6, 1, 2, 3, 7, 8, 9]

**Comment by drakeltheryuujin** [comment]
Hi @atxrenegade,
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
